name: 'dart-package-inspector'
description: 'Inspect dart/Flutter packages for a certain criteria'
author: 'fujidaiti'
inputs:
  report:
    description: 'JSON output of pana'
    required: true
  min-pub-points:
    description: 'Required minimum Pub points'
    default: 0
runs:
  using: 'node16'
  main: 'dist/index.js'
